-- Snowflake Cost Report - Database Setup
-- Run this script with ACCOUNTADMIN role to create all required objects.

USE ROLE ACCOUNTADMIN;

-- 1. Database and Schema
CREATE DATABASE IF NOT EXISTS COSTS_DB;
CREATE SCHEMA IF NOT EXISTS COSTS_DB.REPORTING;

-- 2. Email Recipients Table
CREATE TABLE IF NOT EXISTS COSTS_DB.REPORTING.EMAIL_RECIPIENTS (
    EMAIL VARCHAR NOT NULL,
    NAME VARCHAR,
    ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 3. Report Schedule Table (reference/documentation of send times)
CREATE TABLE IF NOT EXISTS COSTS_DB.REPORTING.REPORT_SCHEDULE (
    SCHEDULE_ID INT AUTOINCREMENT,
    SEND_HOUR INT NOT NULL,
    SEND_MINUTE INT NOT NULL DEFAULT 0,
    TIMEZONE VARCHAR DEFAULT 'Europe/London',
    ACTIVE BOOLEAN DEFAULT TRUE,
    DESCRIPTION VARCHAR,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 4. Internal Stage for Excel Reports
CREATE STAGE IF NOT EXISTS COSTS_DB.REPORTING.REPORT_STAGE
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');
